2024-12-07 19:51:14,824 - INFO - Starting the migration process.
2024-12-07 19:51:14,824 - INFO - Snowflake Credentials: {'user': 'EC528AUTOMATION3', 'password': '********', 'account': 'orhmmra-ypb57008', 'warehouse': 'COMPUTE_WH', 'database': 'TEST', 'schema': 'PUBLIC'}
2024-12-07 19:51:14,824 - INFO - Connecting to Snowflake...
2024-12-07 19:51:14,825 - INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.9.15, Platform: macOS-13.3.1-x86_64-i386-64bit
2024-12-07 19:51:14,825 - INFO - Connecting to GLOBAL Snowflake domain
2024-12-07 19:51:14,825 - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-12-07 19:51:15,560 - INFO - Connection to Snowflake established successfully.
2024-12-07 19:51:15,665 - INFO - Number of results in first chunk: 1
2024-12-07 19:51:15,665 - INFO - Database TEST created successfully (if it didn't already exist).
2024-12-07 19:51:15,742 - INFO - Number of results in first chunk: 1
2024-12-07 19:51:15,846 - INFO - Number of results in first chunk: 1
2024-12-07 19:51:15,846 - INFO - Schema PUBLIC created successfully.
2024-12-07 19:51:15,846 - INFO - closed
2024-12-07 19:51:15,897 - INFO - No async queries seem to be running, deleting session
2024-12-07 19:51:15,950 - INFO - Connecting to Snowflake...
2024-12-07 19:51:15,950 - INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.9.15, Platform: macOS-13.3.1-x86_64-i386-64bit
2024-12-07 19:51:15,951 - INFO - Connecting to GLOBAL Snowflake domain
2024-12-07 19:51:15,951 - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-12-07 19:51:16,217 - INFO - Connection to Snowflake established successfully.
2024-12-07 19:51:16,360 - INFO - Number of results in first chunk: 1
2024-12-07 19:51:16,459 - INFO - Number of results in first chunk: 0
2024-12-07 19:51:16,531 - INFO - Number of results in first chunk: 0
2024-12-07 19:51:16,532 - INFO - Successfully retrieved database objects.
2024-12-07 19:51:16,532 - INFO - closed
2024-12-07 19:51:16,587 - INFO - No async queries seem to be running, deleting session
2024-12-07 19:51:16,681 - INFO - Total changesets generated: 1
2024-12-07 19:51:16,685 - INFO - Changelog written to migrations/generated_changelog_20241207_195115.yaml
2024-12-07 19:51:16,688 - INFO - Changelog validation successful. Total changesets: 1
2024-12-07 19:51:16,688 - INFO - Changeset IDs:
2024-12-07 19:51:16,689 - INFO -   create-template-warehouse
2024-12-07 19:51:16,689 - INFO - Constructed Snowflake URL: jdbc:snowflake://orhmmra-ypb57008.snowflakecomputing.com/?user=EC528AUTOMATION3&password=********&warehouse=COMPUTE_WH&database=TEST&schema=PUBLIC
2024-12-07 19:51:16,689 - INFO - Starting Liquibase migration using changelog: migrations/generated_changelog_20241207_195115.yaml
2024-12-07 19:51:20,763 - INFO - Running migration with command: liquibase --changeLogFile=migrations/generated_changelog_20241207_195115.yaml --url=jdbc:snowflake://orhmmra-ypb57008.snowflakecomputing.com/?user=EC528AUTOMATION3&password=Chesterfield4396@&warehouse=COMPUTE_WH&database=TEST&schema=PUBLIC --defaultSchemaName=PUBLIC update
2024-12-07 19:51:24,018 - ERROR - Error running Liquibase migration:
Command: ['liquibase', '--changeLogFile=migrations/generated_changelog_20241207_195115.yaml', '--url=jdbc:snowflake://orhmmra-ypb57008.snowflakecomputing.com/?user=EC528AUTOMATION3&password=Chesterfield4396@&warehouse=COMPUTE_WH&database=TEST&schema=PUBLIC', '--defaultSchemaName=PUBLIC', 'update']
Return Code: 1
STDOUT: 
STDERR: ####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##                                                ##
####################################################
Starting Liquibase at 19:51:23 using Java 21.0.4 (version 4.29.2 #3683 built at 2024-08-29 16:45+0000)
Liquibase Version: 4.29.2
Liquibase Open Source 4.29.2 by Liquibase
ERROR: Exception Details
ERROR: Exception Primary Class:  ClassCastException
ERROR: Exception Primary Reason:  class java.lang.String cannot be cast to class liquibase.database.Database (java.lang.String is in module java.base of loader 'bootstrap'; liquibase.database.Database is in unnamed module of loader java.net.URLClassLoader @6442b0a6)
ERROR: Exception Primary Source:  4.29.2

Unexpected error running Liquibase: class java.lang.String cannot be cast to class liquibase.database.Database (java.lang.String is in module java.base of loader 'bootstrap'; liquibase.database.Database is in unnamed module of loader java.net.URLClassLoader @6442b0a6)

For more information, please use the --log-level flag

2024-12-07 19:51:24,019 - ERROR - Migration process failed: Command '['liquibase', '--changeLogFile=migrations/generated_changelog_20241207_195115.yaml', '--url=jdbc:snowflake://orhmmra-ypb57008.snowflakecomputing.com/?user=EC528AUTOMATION3&password=Chesterfield4396@&warehouse=COMPUTE_WH&database=TEST&schema=PUBLIC', '--defaultSchemaName=PUBLIC', 'update']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/ricardoxu/Desktop/automation-snowflake-harness/main.py", line 65, in main
    migration_manager.run_migration(changelog_file)
  File "/Users/ricardoxu/Desktop/automation-snowflake-harness/scripts/migration_manager.py", line 94, in run_migration
    result = subprocess.run(update_command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
  File "/Users/ricardoxu/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['liquibase', '--changeLogFile=migrations/generated_changelog_20241207_195115.yaml', '--url=jdbc:snowflake://orhmmra-ypb57008.snowflakecomputing.com/?user=EC528AUTOMATION3&password=Chesterfield4396@&warehouse=COMPUTE_WH&database=TEST&schema=PUBLIC', '--defaultSchemaName=PUBLIC', 'update']' returned non-zero exit status 1.
